### ISSUE TITLE
Open Links in Background Without Displaying Context Menu

### ISSUE THREAD

**Issue by Mehmuod** [Etheryte/right-click-opens-link-in-a-background-tab#2]
The current functionality of the extension serves its purpose well. However, I don't want the context menu to show up every time I do that.
I suggest modifying the extension to eliminate the display of the context menu when right-clicking on a link.

**Comment by Etheryte** [comment]
Could you please provide some more details? What operating system are you on and/or what page is this happening on? Or does this happen on all pages you visit. More details would be helpful as currently I'm not able to replicate the issue, for me the context menu is hidden.

**Comment by Mehmuod** [comment]
More details:
https://github.com/Etheryte/right-click-opens-link-in-a-background-tab/assets/89402290/d64406c6-73aa-4cc3-90b3-5666b9260520

Windows 11 Pro.
Happens on any webpage.

**Comment by Mehmuod** [comment]
> More details: https://github.com/Etheryte/right-click-opens-link-in-a-background-tab/assets/89402290/d64406c6-73aa-4cc3-90b3-5666b9260520
> 
> Windows 11 Pro. Happens on any webpage.

More details:
https://github.com/Etheryte/right-click-opens-link-in-a-background-tab/assets/89402290/d64406c6-73aa-4cc3-90b3-5666b9260520

Windows 11 Pro.
Happens on any webpage.

**Comment by Etheryte** [comment]
Thanks a lot for the info, seems like the event firing order differs on Windows. I've addressed this in https://github.com/Etheryte/right-click-opens-link-in-a-background-tab/commit/d48fa9794bddccdedc61922e71b628978b28d8bc, the change is also submitted to the extension and the update will be available as soon as the extension update is reviewed.
