### ISSUE TITLE
Broken link at https://www.youtube.com/watch?v=A1IaTYdF6eQ

### ISSUE THREAD

**Issue by QADER86** [Etheryte/right-click-opens-link-in-a-background-tab#3]
**Is the affected page a public page?**

If the page is not public I can't help you with your issue. I can't debug what I can't access, sorry.  
To check the checkbox, put an `x` between the brackets below: `[ ]` -> `[x]`

 - [ ] Yes, it is a public page

**Where is the link on that page?**

Please insert either a screenshot or a description of where the link is to help me find it:

**Comment by Etheryte** [comment]
Please specify which link on the page doesn't work, as far as I've currently checked, all links on Youtube seem to work fine.
