### ISSUE TITLE
Broken link at https://www.sxzlzx.cn/article-32664?cid=318

### ISSUE THREAD

**Issue by Grass-Life** [Etheryte/right-click-opens-link-in-a-background-tab#5]
**Is the affected page a public page?**

If the page is not public I can't help you with your issue. I can't debug what I can't access, sorry.  
To check the checkbox, put an `x` between the brackets below: `[ ]` -> `[x]`

 - [ ] Yes, it is a public page

**Where is the link on that page?**

Please insert either a screenshot or a description of where the link is to help me find it:

**Comment by Etheryte** [comment]
Template not filled out.
