### ISSUE TITLE
Broken link at https://www.coupang.com/np/categories/498705

### ISSUE THREAD

**Issue by lnbworld** [Etheryte/right-click-opens-link-in-a-background-tab#6]
**Is the affected page a public page?**

If the page is not public I can't help you with your issue. I can't debug what I can't access, sorry.  
To check the checkbox, put an `x` between the brackets below: `[ ]` -> `[x]`

 - [x] Yes, it is a public page

**Where is the link on that page?**

Please insert either a screenshot or a description of where the link is to help me find it:

**Comment by lnbworld** [comment]
![Uploading 1.jpg…]()

**Comment by Etheryte** [comment]
Thanks for the bug report, at the moment it looks like the screenshot didn't upload. Could you please retry?

**Comment by Etheryte** [comment]
Closing as no reply.
