### ISSUE TITLE
https://www.netsuite.com/portal/in/customer-testimonials.shtml#

### ISSUE THREAD

**Issue by gauravrana7** [Etheryte/right-click-opens-link-in-a-background-tab#7]
**Is the affected page a public page?**

If the page is not public I can't help you with your issue. I can't debug what I can't access, sorry.  
To check the checkbox, put an `x` between the brackets below: `[ ]` -> `[x]`

 - [ ] Yes, it is a public page

**Where is the link on that page?**

Please insert either a screenshot or a description of where the link is to help me find it:

**Comment by Etheryte** [comment]
Closing as the template is not filled out.
